### ISSUE TITLE
linked_clone don't work on VirtualBox 4.1

### ISSUE THREAD

**Issue by md55** [mitchellh/vagrant#7049]
Vagrant 1.8.1
VirtualBox 4.1.16 r78094
Windows 7 x64 Ultimate SP1

```ruby
  config.vm.box = "hashicorp/precise64"
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end
```

```
c:\HashiCorp\test_project>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualb
ox/action/prepare_clone_snapshot.rb:44:in `prepare_snapshot': undefined method `
list_snapshots' for #<VagrantPlugins::ProviderVirtualBox::Driver::Version_4_1:0x
2c708e8> (NoMethodError)```
