### ISSUE TITLE
WinRM tries to use host machine proxy settings during provision

### ISSUE THREAD

**Issue by digitaldrummerj** [mitchellh/vagrant#6273]
On a Windows host, when I do a vagrant up or vagrant provision,  if I have the http_proxy and https_proxy system environment variables I get WinRM powershell errors.  If I remove my http_proxy and https_proxy system environment variables it works everytime.

```
    ==> default: Running provisioner: shell...
    An error occurred executing a remote WinRM command.

    Shell: powershell
    Command: hostname
    if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1
     } }
    Message: Unable to parse WinRM response: #<REXML::ParseException: No close tag f
    or /HTML>
    C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rexml/parsers/treeparser.rb:28:in `
    parse'
    C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rexml/document.rb:287:in `build'
    C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rexml/document.rb:43:in `initialize'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:42:in `new'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:42:in `response_xml'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:61:in `raise_if_wsman_fault'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:51:in `raise_if_error'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:35:in `parse_to_xml'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/http/transport.rb:50:in `send_request'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/winrm_service.rb:430:in `send_message'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/winrm_service.rb:126:in `open_shell'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/winrm_service.rb:299:in `run_cmd'
    C:/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/winrm_service.rb:317:in `run_powershell_script'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/shell.rb:93:in `block in execute_shell_with_retry'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/retryable.rb:17:in `retryable'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/shell.rb:91:in `execute_shell_with_retry'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/shell.rb:84:in `execute_shell'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/shell.rb:57:in `powershell'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/communicator.rb:99:in `block in ready?'
    C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/communicator.rb:98:in `ready?'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:249:in `guest'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/shell/provisioner.rb:94:in `provision_winrm'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/shell/provisioner.rb:22:in `provision'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:133:in `run_provisioner'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in `hook'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:121:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:121:in `block in call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:103:in `each'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:103:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/provision/command.rb:30:in `block in execute'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/provision/command.rb:29:in `execute'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
    ...
    No close tag for /HTML
    Line: 3
    Position: 81
    Last 80 unconsumed characters:
     (301).
```

**Comment by quinz** [comment]
I have exactly same behavior on a Linux (Ubuntu 14.04) host. I'm trying to set up a Windows box with HTTP and HTTPS proxies.

**Comment by patthoyts** [comment]
This has been giving me trouble since upgrading to 1.7.4 on Windows using Windows guests where any provisioning scripts returned the following output:

    An error occurred executing a remote WinRM command.
    
    Shell: powershell
    Command: hostname
    if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
    Message: undefined method `text' for nil:NilClass

Unsetting `http_proxy` and `https_proxy` has allowed provisioning to run normally again.

(I've put the error output in to assist other people running into this problem in finding this bug report.)

**Comment by sfhardman** [comment]
You can also get around this issue by setting a NO_PROXY environment variable to 127.0.0.1

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
