### ISSUE TITLE
Windows: unable to install plugin using local gem file

### ISSUE THREAD

**Issue by rrzaripov** [mitchellh/vagrant#8425]
### Vagrant version
Vagrant 1.9.3

### Host operating system
Microsoft Windows 10 Pro 10.0.10240

### Guest operating system
Guest no needed

### Vagrantfile
Vagrantfile no needed

### Debug output
[reproduce step 3](https://gist.githubusercontent.com/rrzaripov/4ee95ea05918916a5ad22cd20141f40d/raw/624988040724241e9cc9c182df57237b847ad3b7/gistfile1.txt)
[reproduce step 4](https://gist.githubusercontent.com/rrzaripov/04ca02a9c3dc2bf636e5ec6c66a1ba5f/raw/4bb7628eb24ad8109e294ee5f5664cee754b0320/gistfile1.txt)
[reproduce step 5](https://gist.githubusercontent.com/rrzaripov/2e6ec64d2cd418d2e5abd66ec6884a63/raw/651b6632da43bfa682b6d55bca6a06d775c65801/gistfile1.txt)

### Expected behavior
Plugin installed successful.

### Actual behavior
Plugin not installed

### Steps to reproduce
1. [Download](https://rubygems.org/downloads/vagrant-triggers-0.5.3.gem) vagrant-triggers gem file 
2. Change directory to the where downloaded gem saved
3. `vagrant plugin install vagrant-triggers-0.5.3.gem`
**`fetch_path': undefined method `fetch_d'**  
OK, maybe im using wrong URI?
4. `vagrant plugin install file://D:/Install/vagrant-triggers-0.5.3.gem`
`initialize': Invalid argument @ rb_sysopen - **D:/Install/file:/D:/Install/vagrant-triggers-0.5.3.gem** 
(Errno::EINVAL) 
Interesting file path...
5. `vagrant plugin install vagrant-triggers --plugin-source file://d:/install/ --plugin-version 0.5.3`

```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: 'vagrant-triggers (= 0.5.3)' requires 'bundler (~> 1.3)'
```

In debug log:
DEBUG bundler: Current source list for install: [**"file://d/install/"**, "https://rubygems.org/", "https://gems.hashicorp.com/"]
This URL is correct?

Exist any workaround (another than downgrade to version 1.7.4)?

**Comment by chrisroberts** [comment]
Hi there. This has been fixed via #8401 and will be included in the next release. As a work around until release you can use the UNC path style:

```
$ vagrant plugin install \\?\d:\Install\vagrant-triggers-0.5.3.gem
```

Cheers!

**Comment by rrzaripov** [comment]
Seems not work in 1.9.4:

```
D:\Install>vagrant plugin install specs.4.8 --plugin-source file://d:/install/ --plugin-version 4.8
Installing the 'specs.4.8 --version '4.8'' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  Errno::ETIMEDOUT: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for "api.rubygems.org" port 443 (https://api.rubygems.org/specs.4.8.gz)

Source: https://rubygems.org/
```
P.S. specs.4.8.gz saved in D:\install
