### ISSUE TITLE
Vagrant 1.9.1 break 'service-manager' plugin 'install-cli' command

### ISSUE THREAD

**Issue by budhrg** [mitchellh/vagrant#8259]
Hi,

We have been using Vagrant to provide cross platform development environment for [ADB](https://github.com/projectatomic/adb-atomic-developer-bundle).

One of plugin i.e [service-manager](https://github.com/projectatomic/vagrant-service-manager) is now breaking for ['install-cli'](https://github.com/projectatomic/vagrant-service-manager/blob/master/commands.adoc#install-cli) command when upgrading to version 1.9.1.

This was working fine in Vagrant version `1.8.1`.

Error is :
```
$ vagrant service-manager install-cli docker
undefined method `upcase' for nil:NilClass
```

After bit of debugging we found that [this line](https://github.com/projectatomic/vagrant-service-manager/blob/master/plugins/guests/redhat/cap/os_variant.rb#L10) return empty since `data` seems to be empty.
Further debugging shows us that now `data` part fills on second iteration as:
```
$ vagrant service-manager install-cli docker
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
================== before execute in os_variant ============
data: , type: stdout
data: VARIANT_ID="adb", type: stdout
================== after execute in os_variant ============
undefined method `upcase' for nil:NilClass
``` 

#### We would be interested to know, is there any design change here? For us, the fix seems to be simple as [this PR](https://github.com/projectatomic/vagrant-service-manager/pull/453). More question in comment https://github.com/projectatomic/vagrant-service-manager/pull/453#discussion_r99364513 as
> No way that this gets executed twice by design. Either there is a bug in Vagrant or we are missing something else. 
> If there is indeed something we need to workaround we need a better patch than this. What if for some reason we need another communicator call somewhere else? How would one kn ow/remember to add this next statement. If there is a workaround needed we need to provide a way to apply this workaround to all potential uses of the communicator, for example by adding our own helper/utility method around the communicator here.

*Steps to reproduce*
- vagrant init projectatomic/adb
- vagrant plugin install vagrant-service-manager
- vagrant up
- vagrant service-manager install-cli docker

**Comment by chrisroberts** [comment]
Is this an issue with Windows specifically, or other host/guest combinations as well?

**Comment by budhrg** [comment]
@chrisroberts ,

I am facing it in Windows and Linux (didn't have Mac). Seems to be some api change post 1.8.1 version.

**Comment by shepp67** [comment]
I'm running into this issue right now with the CDK image running on Mac OSX Yosemite, and VirtualBox 5.1
Is there a way I can downgrade my vagrant to 1.8.1 to get this working?

_BDS00818:rhel-ose jsheppard$ vagrant service-manager install-cli openshift
undefined method `upcase' for nil:NilClass_

**Comment by budhrg** [comment]
@shepp67 You can downgrade the version by uninstalling vagrant 1.9.1 and download older version of vagrant from here https://releases.hashicorp.com/vagrant/

**Comment by shepp67** [comment]
Ty, giving that a go today!
